import type { Metadata } from "next";
import { Geist, Geist_Mono, Dancing_Script } from "next/font/google";
import "../shared/styles/globals.css";
import Header from "@/features/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistDancing = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistDancing.variable} min-h-screen max-h-screen min-w-screen max-w-screen flex flex-col justify-start items-center`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
